# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Spark-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Spark-iOS
  pod 'SnapKit', '~> 5.0.0'
  pod 'Kingfisher', '~> 7.0'
  pod 'SwiftLint'
  pod 'Moya', '~> 15.0'
  pod 'JJFloatingActionButton'
  pod 'KakaoSDKCommon'
  pod 'KakaoSDKUser'
  pod 'KakaoSDKAuth'
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
  pod 'lottie-ios'
  pod 'Kingfisher', '~> 7.0'
end
