# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    get_certificates
    get_provisioning_profile
    increment_build_number(xcodeproj: "Spark-iOS.xcodeproj")
    build_app(workspace: "Spark-iOS.xcworkspace", scheme: "Spark-beta")
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
    version = get_version_number
    build = get_build_number 
    slack(
        username: "항상건강해야한다콩이",
        icon_url: "https://user-images.githubusercontent.com/69136340/194049016-4b1f747f-99ed-4a14-a28d-2ed9a26fe0e3.png",
        message: "성공적으로 TestFilight 에 등록되었습니다!🔥",
        slack_url: "https://hooks.slack.com/services/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",
        payload: {
	  "Version": version + "(" + build + ")"
        }
    )
  end
  end
end
