# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    get_certificates
    get_provisioning_profile
    increment_build_number(xcodeproj: "Spark-iOS.xcodeproj")
    build_app(
      workspace: "Spark-iOS.xcworkspace",
      scheme: "Spark-beta",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: { 
          "com.TeamSparker.Spark" => "com.TeamSparker.Spark AppStore",
          "com.TeamSparker.Spark.SparkNotificationService" => "com.TeamSparker.Spark.SparkNotificationService AppStore"
        }
      }
    )
    upload_to_testflight(
      api_key_path: "fastlane/key.json",
      distribute_external: true,
      groups: ["SparkBetaTestGroup"],
      changelog: "- 수출 규정 문서 추가
- fastlane 에서 테스트 세부사항 작성"
    )
    version = get_version_number(
                xcodeproj: "Spark-iOS.xcodeproj",
                target: "Spark-iOS"
              )
    build = get_build_number 
    slack(
      username: "항상건강해야한다콩이",
      icon_url: "https://user-images.githubusercontent.com/69136340/194049016-4b1f747f-99ed-4a14-a28d-2ed9a26fe0e3.png",
      message: "성공적으로 TestFlight 에 등록되었습니다!🔥",
      slack_url: "https://hooks.slack.com/services/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",
      payload: {
	"Version": version + "(" + build + ")"
      }
    )
  end

  desc "Push a new release build to the App Store"
  lane :release do |options|
    if options[:version]
      get_certificates
      get_provisioning_profile
      increment_version_number(version_number: options[:version])
      build_app(workspace: "Spark-iOS.xcworkspace", scheme: "Spark-release")
      upload_to_app_store(
        api_key_path: "fastlane/key.json",
        skip_metadata: false,
        skip_screenshots: true,
        submit_for_review: true,
        automatic_release: true,
        force: true
      )
      version = get_version_number(
                xcodeproj: "Spark-iOS.xcodeproj",
                target: "Spark-iOS"
              )
      build = get_build_number 
      slack(
        username: "항상건강해야한다콩이",
        icon_url: "https://user-images.githubusercontent.com/69136340/194049016-4b1f747f-99ed-4a14-a28d-2ed9a26fe0e3.png",
        message: "성공적으로 앱을 등록했습니다!💫",
        slack_url: "https://hooks.slack.com/services/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",
        payload: {
	  "Version": version + "(" + build + ")"
        }
      )
    end
  end

  error do |lane, exception, options|
    version = get_version_number(
                xcodeproj: "Spark-iOS.xcodeproj",
                target: "Spark-iOS"
              )
    build = get_build_number 
    slack(
      username: "항상건강해야한다콩이",
      icon_url: "https://user-images.githubusercontent.com/69136340/194049016-4b1f747f-99ed-4a14-a28d-2ed9a26fe0e3.png",
      message: "에러 발생!!! 발생!!🚨 : #{exception}",
      success: false,
      slack_url: "https://hooks.slack.com/services/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",
      payload: {
	"Version": version + "(" + build + ")"
      }
    )
  end
end
